### ISSUE TITLE
Is this project open to contributions?

### ISSUE THREAD

**Issue by srivarra** [saeyslab/harpy#71]
Hello, I'm one of the maintainers of [ark-analysis](https://github.com/angelolab/ark-analysis) and this is shaping up to be a great modernized toolkit for spatial proteomics. Are contributions welcome? I'd love to help out with development (features, CI / CD, testing, documentation, datasets, etc...).

**Comment by berombau** [comment]
Hi, thank you for the interest, I'm open for contributions. Feel free to reach out via chat (Benjamin Rombaut @ imagesc Zulip) or e-mail (benjamin.rombaut@gmail.com) to specify this a bit more. I'm at a conference this week, but if you want to link up next week online, here is a [poll](https://rallly.co/invite/rHNc1NqN1gTV) to find a meeting time.

**Comment by berombau** [comment]
Closing this now, but for anyone feel free to make an Issue or PR or contact me via the details above.
